### ISSUE TITLE
Invalid payload during setup.

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj-core#10]
Error running `mlproj setup` on MarkLogic 9.0-1.1

**Error:**
✗ Create server:                foo
Entity not created: MANAGE-INVALIDPAYLOAD: (err:FOER0000) Payload has errors in structure, content-type or values. Server root missing.

I see the request is a POST request with:
the following url and payload:
URL: /servers?group-id=Default
PAYLOAD:  {"server-name":"foo","server-type":"http","content-database":"foo-content","port":9110}

Tested on windows and ubuntu

**Comment by eurochriskelly** [comment]
I notice that the default properties for server in base.json include:

        `"servers": [{
            "id": "app",
            "name": "@{code}",
            "type": "http",
            "port": "${port}",
            "content": {
                "idref": "content"
            }
        }]`

By adding "root": "/" this works. Nevertheless, any reason why root=/ or modules is not added by default anymore?

**Comment by fgeorges** [comment]
Thank you Chris.  The base environment is not a complete one, it is the base for dev and prod, resp. having no modules database (root is the dir `src` on the filesystem) and having a modules database (root is then "/").  It is not supposed to be used directly, just when imported through another one.

The default environment is typically set to dev.

One thing to change though, is trying to detect the precise error (the MarkLogic API does not make that easy) and display it more clearly.

**Comment by eurochriskelly** [comment]
I did not change the default environment. I just ran the following commands in a new folder

```
mlproj new # filled out inputs
mlproj setup
```

using mlproj version 0.46.1, fyi

**Comment by fgeorges** [comment]
So actually, it seems there is a bug indeed.  It is not related to base, it is the fact that if you do not have a modules database on a server, it uses the source directory.  Used to be a "global" source dir, which was got rid of when introducing the source sets, but then it fails now to set it in case of working on the filesystem.

I could narrow the change to blame around the commit b51c58d.  Need more time to decide how to fix it.

As per the default environment, it is mlenvs/default.json.  By default, it simply imports dev.json.  `mlproj show` gives the details...

**Comment by fgeorges** [comment]
So quick summar of the issue:

- mlproj used to have a global source dir
- it defaulted to `src`
- it was used for app server with no modules db
- it has been removed when introducing source sets
- using the filesystem for modules of a server was not replaced by source sets

In order to fix it, I would like to use the same machanism used in `deploy` to
resolve which directory or source set to use:

- an explicit one
- by default use the source set with name `src` if any

The explicit one essentially requires to be able to link databases and servers
to source sets in the environs.  That is beyond the scope of this ticket, but
that is the idea.

**Comment by fgeorges** [comment]
Should be fixed by 36626be (the part about using default source set `src` if any, not linking servers to source sets).

Can you please confirm it?

**Comment by eurochriskelly** [comment]
Works with mlproj-core 0.24.2
