### ISSUE TITLE
Allow composite sources

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj-core#18]
Source code may not always be one folder. For example, using a component architecture one might have the following layout:

```
xprojects
components\
  comp-A\
    src\
    data\
  comp-B\
    src\
common\
   src\   
```

Would it be possible to allow for multiple source/data folders? 

One way thing could be achieved is using the following alternative config - supporting strings and arrays for the **dir** property:
```
sources[{
  name: "src",
  dir: ["components/comp-A/src", "components/comp-B/src"]
}]            
```
To achieve this you could do something like this in components.js:
Replace:
```
const path = ctxt.platform.resolve(dir);
this.walkDir(onMatch, '', dir, path, path, patterns, ctxt, display);
```
with
```
const walk = (d) => {
    const path = ctxt.platform.resolve(d);
    this.walkDir(onMatch, '', d, path, path, patterns, ctxt, display);
}

if (Array.isArray(dir)) {
    dir.forEach(walk);
} else {
    walk(dir);
}
```

I've tried this locally and it seems to work fine. However, this may be too simplistic going forward. What do you think?

**Comment by fgeorges** [comment]
Seems to be covered by #17 as well, to be confirmed.  Comment above contains also pieces of code for implementation of #17.

**Comment by eurochriskelly** [comment]
Yes. Most definitely. If you plan to implement it that way I'll close this issue.
