### ISSUE TITLE
mlproj new existing folder

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj-core#2]
wanted to convert a project using mlproj but new doesn't like if folder has content. I can run git init or npm init in an existing folder. Why not mlproj.

**Comment by fgeorges** [comment]
The reason is, I wanted to be "defensive" in case we are in a non-empty dir.  Just to be sure a user does not mess up with his/her filesystem.

I guess it should ask in that case the user whether he/she wants to proceed.  What do you think?

**Comment by eurochriskelly** [comment]
Perhaps a force flag (-f) would help. Also, if the folders don't already exist, you could go ahead and make them without any problem.

**Comment by eurochriskelly** [comment]
Tried the latest version but something goes wrong during new/init. I get the following error:

--- Questions ---                                                                                                                                                           
Project code    : abc                                                                                                                                                        
Title           : def                                                                                                                                                        
Name URI (http://mlproj.org/example/abc): http://localhost/abc                                                                                                              
Version  (0.1.0): 0.1.0                                                                                                                                                      
Port     (8080) : 8087

/tmp/mlp/node_modules/mlproj-core/src/commands.js:69                                                                                                                         
            var actions = new act.ActionList(pf);                                                                                                                            ReferenceError: pf is not defined

This prevents me from testing my other issue.

**Comment by fgeorges** [comment]
Thank you Chris.  Yes, a bug has been introduced with `new` during last big refactoring.  Fixed in the latest 0.33.0.  Sorry about that.

**Comment by fgeorges** [comment]
0.35.0 implements the following:

- if dir not empty, ask the user whether to continue
- if a file or dir exist when tried to be created, it fails unless the flag `--force`

The lag `--force` is a flag to the command `new`, not global to `mlproj`.

So if you try to init an existing dir, you say "y" (yes, I want to proceed on a non-empty dir), and by default (without explicit `--force`), no file will be overwritten under `xproject/`.

I let you test and close the ticket if this solves your issue :-)
