### ISSUE TITLE
When deploying rest services the modules should installed relative to /root

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj-core#21]
Given the structure:
```
ml-modules\
   root\library.sjs
   services\endpoint.sjs
```
... if I deploy a source of type `rest-srv` with dir=ml-modules, it will install the library to `/root/library.sjs`. To be compatible with gradle, it should install to `/libary.sjs`.

**Comment by eurochriskelly** [comment]
Current workaround is to deploy the libraries in a separate step using a named source. This are the run in series using npm-run-all and combining npm scripts.

**Comment by fgeorges** [comment]
For now, the definition of `rest-src` is:

- `services/*` are installed as REST extensions
- `transforms/*` are installed as REST transforms
- everything else is deployed "as is"

and you suggest we replace last point by:

- `root/*` are deployed as a plain source set on its own
- everything else is an error

Correct?

**Comment by fgeorges** [comment]
Related to #20 (which is about first deploy `root/`, then look at `services/` and `transforms/`).

**Comment by fgeorges** [comment]
Should be fixed in latest mlproj, 0.46.5.  @eurochriskelly, can you check and close the issue?

**Comment by eurochriskelly** [comment]
These are installed in the expected location now. Thanks!
