### ISSUE TITLE
ignore file for load data

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj-core#4]
When I load data,  everything in the data folder gets uploaded. It would be nice to have an ignore file to avoid uploading temp emacs files, for example.

**Comment by fgeorges** [comment]
Fixed, see for example `mlproj` 0.42.0.  Some extra notes on this topic...

    "filter": "require('./my-filter.js').filter"

    "filter": "f => f.isIncluded && ! f.isExcluded"

    "filter": [
       "function(desc) {",
       "   return desc.isIncluded && ! desc.isExcluded;",
       "}"
    ]

    "filter": [
       "return desc.isIncluded && ! desc.isExcluded;"
    ]

    "filter": {
       "script":   "my-filter.js",
       "function": "filter"
    }

With `my-filter.js`:

    "use strict";
    (function() {
        function filter() {
            return desc.isIncluded && ! desc.isExcluded;
        }
        module.exports = {
            filter : filter
        }
    }
    )();

With param `desc`:

    let desc = {
        base       : '/full/path/to/base/src',
        path       : '/this/entry.xml',
        full       : '/full/path/to/base/src/this/entry.xml',
        name       : 'entry.xml',
        isdir      : false,
        isIncluded : true,
        isExcluded : false,
        include    : ['*.xqy', '*.xml'],
        exclude    : ['*.md'],
    };

In case of dir, return truthy to keep recursing, falsy to stop recursion.

In case of file, return falsy to not include the file.  If truthy, must be an object with prop `uri` for the URI to use on the database (prop `path` is used by default, so you can just return `desc` and the relative path will be used as URI).  The content is read from a file, the path to which is `full`, or if does not exist `path` (resolved against base source set dir).

**Comment by eurochriskelly** [comment]
Thanks!
