### ISSUE TITLE
Version command

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj-core#5]
I was looking for a version command but could not find anything. This would be useful so I know I've upgraded correctly. Also, I like to be able to compare my local node_modules/.bin/mlproj version with the globally installed version. It would also be good if non-existing switches  - such as "mlproj -V" - would print a friendlier message.

**Comment by fgeorges** [comment]
Released in 0.34.0.

**Comment by eurochriskelly** [comment]
Works. Thanks!

**Comment by fgeorges** [comment]
Good, thank you, Chris!
